<h2>eTokens Sidebar</h2>

<?php
	$visitorStatus = Mage::getSingleton('customer/session');

	if($visitorStatus->isLoggedIn()) {
	  	$customerId = $visitorStatus->getCustomer()->getId();

	  	$collection = Mage::getModel('etokens/etokens')->getCollection()
	  						->addFieldToFilter('customer_id', $customerId);

	  	echo "Amount of tokens: " . $collection->getSize();

	} else {
	  	echo "Log in to view tokens";
	}
?>
